### PR TITLE
Fix CWE-563 from LGTM

### LINKED ISSUE #171: Mitigating security vulnerability analysis from LGTM
_Originally related to PR #170 proposed by @tdrozdovsky_

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

Fix unused ServiceExecutionInfo variable.

Fixes #171 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

The result can be viewed after the update LGTM 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/controller/servicemgr/executor/containerexecutor/containerexecutor.go [hunk 1]
```diff
@@ -63,7 +64,7 @@ func GetInstance() *ContainerExecutor {
 }
 
 // Execute executes container service application
-func (c ContainerExecutor) Execute(s executor.ServiceExecutionInfo) error {
+func (c *ContainerExecutor) Execute(s executor.ServiceExecutionInfo) error {
 	c.ServiceExecutionInfo = s
```
Comment (t25kim) [inline src/controller/servicemgr/executor/containerexecutor/containerexecutor.go:68]: Do we need to have `executor.ServiceExecutionInfo` in the [`type ContainerExecutor struct`](https://github.com/lf-edge/edge-home-orchestration-go/blob/9db48c416d504c668a5fad22a0b80f67ab07a506/src/controller/servicemgr/executor/containerexecutor/containerexecutor.go#L45)?
I think we can execute a container with `s` and don't need to save it to `c.ServiceExecutionInfo`.
How do you think?

**Review by t25kim — COMMENTED** [review]
Thank you for the PR!
Please take a look my comment and share your idea.

File: src/controller/servicemgr/executor/containerexecutor/containerexecutor.go (hunk 1 above)
Comment (tdrozdovsky) [reply src/controller/servicemgr/executor/containerexecutor/containerexecutor.go:68]: I think this information may be useful in the future. Right now I have good reason to delete it.

**Comment by MoonkiHong** [comment]
@t25kim @suresh-lc Could you first take a look at this PR? ^__^

**Review by MoonkiHong — APPROVED** [review]
Since the latest PR applies the review feedback from @t25kim, and overall, it looks good to me. Thank you for your great proposal.

**Review by t25kim — APPROVED** [review]
LGTM!

File: src/controller/servicemgr/executor/containerexecutor/containerexecutor.go (hunk 1 above)
Comment (MoonkiHong) [reply src/controller/servicemgr/executor/containerexecutor/containerexecutor.go:68]: > @t25kim I think this information may be useful in the future. Right now I have good reason to delete it. Thank you for question

@tdrozdovsky Please recommend to post up the suggestion from @t25kim, so that we can follow up the regarding consideration in the future, even though we adopt this PR as it is. What do you think? Once we see the posted issue regarding this, I will merge this PR.
