### PR TITLE
Integration staticcheck tool to CI and fix some warnings

### LINKED ISSUE #323: Use Staticcheck instead of golint
_NOTE: Golint is deprecated and frozen. There's no drop-in replacement for it, but tools such as [Staticcheck](https://staticcheck.io/) and go vet should be used instead._ from https://github.com/golang/lint/blob/master/README.md

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

Since the `lint` project is frozen, @t25kim and me suggest adding a `staticcheck` tool for code analysis.
Thank you @t25kim for a good idea!

Fixes #323 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Code cleanup/refactoring

# How Has This Been Tested?

```
$ make staticcheck
```

**Test Configuration**:
* Firmware version: Ubuntu 20.04
* Hardware: x86-64
* Toolchain: recommended Docker and Go 1.16 versions
* Edge Orchestration Release: Coconut

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: internal/controller/storagemgr/storagedriver/storagehandler.go [hunk 1]
```diff
@@ -442,20 +442,20 @@ func checkUintValueRange(valueType models.ValueType, val uint64) bool {
 	var isValid = false
 	switch valueType {
 	case models.Uint8:
-		if val >= 0 && val <= math.MaxUint8 {
```
Comment (t25kim) [inline internal/controller/storagemgr/storagedriver/storagehandler.go:445]: The code of checkUintValueRange function has been copied from edgex's [device-rest-go](https://github.com/edgexfoundry/device-rest-go/blob/cbc1fb126fca16d22f986b5cd5c305caa6710614/driver/resthandler.go#L324).
What about contributing this code to Edgex for easy maintenance?

File: internal/controller/storagemgr/storagedriver/storagehandler.go [hunk 2]
```diff
@@ -478,9 +478,7 @@ func checkIntValueRange(valueType models.ValueType, val int64) bool {
 			isValid = true
 		}
 	case models.Int64:
-		if val >= math.MinInt64 && val <= math.MaxInt64 {
-			isValid = true
-		}
+		isValid = true
```
Comment (t25kim) [inline internal/controller/storagemgr/storagedriver/storagehandler.go:481]: The code of checkIntValueRange function has been copied from edgex's [device-rest-go](https://github.com/edgexfoundry/device-rest-go/blob/cbc1fb126fca16d22f986b5cd5c305caa6710614/driver/resthandler.go#L324).
What about contributing this code to Edgex for easy maintenance?

File: .github/workflows/lint-vet-gofmt-staticcheck-analysis.yml [hunk 3]
```diff
@@ -18,6 +18,7 @@ jobs:
           go mod tidy
           go get golang.org/x/lint/golint
           echo "$HOME/go/bin" >> $GITHUB_PATH
+          go install honnef.co/go/tools/cmd/staticcheck@latest
 
       - name: Lint Analysis
```
Comment (t25kim) [inline .github/workflows/lint-vet-gofmt-staticcheck-analysis.yml:23]: What do you think excluding Golint work since it's deprecated?

**Review by t25kim — COMMENTED** [review]
Thank you for the contribution!
Please take a look at my comments.

File: internal/controller/storagemgr/storagedriver/storagehandler.go (hunk 1 above)
Comment (tdrozdovsky) [reply internal/controller/storagemgr/storagedriver/storagehandler.go:445]: Thanks for the review. I do not mind to contribute this code. If you have permission, do it. I can't do it, because I need to start approval for this, and it will take some time.

File: .github/workflows/lint-vet-gofmt-staticcheck-analysis.yml (hunk 3 above)
Comment (tdrozdovsky) [reply .github/workflows/lint-vet-gofmt-staticcheck-analysis.yml:23]: As I wrote earlier:

_I propose a lint to not be excluded as it is also useful and used in the Go report system and we have the lowest indicators on it. [golint->76%](https://goreportcard.com/report/github.com/lf-edge/edge-home-orchestration-go)._

But I think that when we fix them then we will exclude lint

File: internal/controller/storagemgr/storagedriver/storagehandler.go (hunk 1 above)
Comment (t25kim) [reply internal/controller/storagemgr/storagedriver/storagehandler.go:445]: My recommendation is not urgent. I'm afraid that you code might be disappeared during next code refactoring with edgex.

File: internal/controller/storagemgr/storagedriver/storagehandler.go (hunk 2 above)
Comment (tdrozdovsky) [reply internal/controller/storagemgr/storagedriver/storagehandler.go:481]: see above

File: internal/controller/storagemgr/storagedriver/storagehandler.go (hunk 1 above)
Comment (tdrozdovsky) [reply internal/controller/storagemgr/storagedriver/storagehandler.go:445]: Well, I will try to make changes in the edgex

**Review by t25kim — APPROVED** [review]
LGTM Thnaks!

**Review by suresh-lc — APPROVED** [review]
Thanks for the changes. deferring the file close for open file pointers after error check is good point.

**Comment by tdrozdovsky** [comment]
Added comments to fix some lint warnings and improve `Go report` rating

File: internal/orchestrationapi/orchestrationapi.go [hunk 4]
```diff
@@ -254,7 +254,7 @@ func getExecCmds(execType string, requestServiceInfos []RequestServiceInfo) ([]s
 		}
 	}
 
-	return nil, errors.New("Not Found")
+	return nil, errors.New("not found")
```
Comment (t25kim) [inline internal/orchestrationapi/orchestrationapi.go:257]: Does all error messages should be written in lowercase?

Comment (tdrozdovsky) [reply internal/orchestrationapi/orchestrationapi.go:257]: Staticcheck determines this as an [error: ST1005 – Incorrectly formatted error string](https://staticcheck.io/docs/checks#ST1005)

**Review by MoonkiHong — APPROVED** [review]
+1 😄

File: internal/controller/storagemgr/storagedriver/storagehandler.go (hunk 1 above)
Comment (tdrozdovsky) [reply internal/controller/storagemgr/storagedriver/storagehandler.go:445]: @t25kim @MoonkiHong Done! Synchronization with the [edgexfoundry/device-rest-go](https://github.com/edgexfoundry/device-rest-go) project made, our changes were [applied](https://github.com/edgexfoundry/device-rest-go/pull/133)
