### PR TITLE
[MNEDC] Change of DB Clearing logic on Network Signal from Kernel

### LINKED ISSUE #271: [MNEDC] Connection failure post Network Reset
**Describe the bug**
Connection failure post Network Reset due to multiple network interface events from kernel in a short time. This bug caused a total MNEDC connection break post reset after DBs got cleared.

**To Reproduce**
1. Run MNEDC server in Main NAT
2. Run MNEDC client in Sub NAT
3. Wait for Error log  "Error in getting network info of <deviceID>"
4. Try Sending a request from Sub to main
5. Try Sending a request from main to sub
6. Both would fail, with SERVICE_NOT_FOUND error
7. Docker logs would make it clear that request for score failed OR there was no auction for other device to get score.

**Expected behavior**
Score should be fetched from remote device and post auction, best device should be chosen to run the service

**Supporting Logs**

> INFO[2021-01-13T16:59:17+05:30]main.go:183 orchestrationInit interface orchestration init done            
> INFO[2021-01-13T16:59:17+05:30]clientcontrol.go:108 getDeviceID [GetDeviceID] Got the UUID                   
> INFO[2021-01-13T16:59:17+05:30]detector_netlink.go:82 detectionHandler detector_netlink [DetectionHandler] New Connection :  10.0.0.1 
> INFO[2021-01-13T16:59:17+05:30]networkhelper.go:216 subAddrChange [networkmgr] true                            
> INFO[2021-01-13T16:59:17+05:30]detector_netlink.go:86 detectionHandler detector_netlink [DetectionHandler] Disconnected :  10.0.0.1 
> INFO[2021-01-13T16:59:17+05:30]networkhelper.go:194 setAddrInfo [networkmgr] addr 192.168.1.29/24            
> INFO[2021-01-13T16:59:17+05:30]networkhelper.go:194 setAddrInfo [networkmgr] addr 10.0.0.1/24                
> INFO[2021-01-13T16:59:17+05:30]networkhelper.go:216 subAddrChange [networkmgr] false                           
> INFO[2021-01-13T16:59:17+05:30]detector_netlink.go:82 detectionHandler detector_netlink [DetectionHandler] New Connection :  10.0.0.1 
> INFO[2021-01-13T16:59:17+05:30]networkhelper.go:194 setAddrInfo [networkmgr] addr 192.168.1.29/24            
> INFO[2021-01-13T16:59:17+05:30]server.go:173 Run [mnedcserver] Server started                 
> INFO[2021-01-13T16:59:17+05:30]networkhelper.go:194 setAddrInfo [networkmgr] addr 10.0.0.1/24                
> INFO[2021-01-13T16:59:17+05:30]networkhelper.go:216 subAddrChange [networkmgr] false                           
> INFO[2021-01-13T16:59:17+05:30]networkhelper.go:194 setAddrInfo [networkmgr] addr 192.168.1.29/24            
> INFO[2021-01-13T16:59:17+05:30]networkhelper.go:194 setAddrInfo [networkmgr] addr 10.0.0.1/24                
> INFO[2021-01-13T16:59:17+05:30]networkhelper.go:249 Notify [networkmgr] [notify]  subchan is not receiving 
> INFO[2021-01-13T16:59:17+05:30]networkhelper.go:216 subAddrChange [networkmgr] true                            
> INFO[2021-01-13T16:59:17+05:30]networkhelper.go:194 setAddrInfo [networkmgr] addr 192.168.1.29/24            
> INFO[2021-01-13T16:59:17+05:30]networkhelper.go:194 setAddrInfo [networkmgr] addr 10.0.0.1/24                
> INFO[2021-01-13T16:59:17+05:30]networkhelper.go:249 Notify [networkmgr] [notify]  subchan is not receiving

 

> [discoverymgr] Error in getting network info of edge-orchestration-19600595-b881-4a47-bc44-50a81a8d94b2

> [orchestrationapi] cannot getting score from : 10.0.0.1 cause by [restclient] get return error 

Post this Requests from Main to Sub and Main to Sub : resuled in a faliure

`curl -X POST http://localhost:56001/api/v1/orchestration/services --data '{"ServiceName": "hello-world","ServiceInfo": [{"ExecutionType":"container","ExecCmd":["docker", "run", "-v", "hello-world"]}],"StatusCallbackURI": "http://localhost:8888/api/v1/services/notification", "ServiceRequester": "curl","SelfSelection": "false"}{"Message":"SERVICE_NOT_FOUND","RemoteTargetInfo":{"ExecutionType":"","Target":""},"ServiceName":"hello-world"}`

**Test environment configuration:**
* Firmware version:  Ubuntu 16.04
* Hardware: x86-64
* Toolchain: Go 15.1
* Edge Orchestration Release:  Coconut

### PR DESCRIPTION
**Pull request by sun-sharma**
Signed-off-by: Sunchit Sharma <sun.sharma@samsung.com>

- Reset DB regarding connected devices when new and del events regarding IPv4 address are up
- SetTUNIP() : Implemented by golang API that give the IP details instead of external ifconfig command
- detectionHandler() returns true when new and del events up

# Description

Connection failure post Network Reset due to multiple network interface events from kernel in a short time. This bug caused a total MNEDC connection break post reset after DBs got cleared. 

Fixes #271 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- A two system setup was taken, Where one system was in Main NAT and other system was in Sub NAT. 
- Main NAT system ran MNEDC Server
- Sub NAT system ran MNEDC Client
- Post this Multiple requests were sent from Sub to Main and Main to Sub and they worked successfully which was verifies from Request outputs and Score Logs

### Request
```
curl -X POST http://localhost:56001/api/v1/orchestration/services --data '{ "ServiceName": "hello-world", "ServiceInfo": [{ "ExecutionType": "container", "ExecCmd":[ "docker", "run", "-v", "/var/run:/var/run:rw", "hello-world"]}], "StatusCallbackURI": "http://localhost:8888/api/v1/services/notification","SelfSelection":"false","ServiceRequester":"curl"}'

{"Message":"ERROR_NONE","RemoteTargetInfo":{"ExecutionType":"container","Target":"10.0.0.2"},"ServiceName":"hello-world"}
```
### Main System Edge Orchestration Logs
```
INFO[2021-02-18T19:30:58Z]orchestrationapi.go:122 RequestService [RequestService] hello-world: [{container [docker run -v /var/run:/var/run:rw hello-world] map[]}] 

INFO[2021-02-18T19:30:59Z]orchestrationapi.go:148 RequestService [RequestService] getCandidate                

INFO[2021-02-18T19:30:59Z]orchestrationapi.go:150 RequestService [0] Id       : edge-orchestration-235d74e7-c62c-464c-8bd8-74443ef41e0c 

INFO[2021-02-18T19:30:59Z]orchestrationapi.go:151 RequestService [0] ExecType : container                     

INFO[2021-02-18T19:30:59Z]orchestrationapi.go:152 RequestService [0] Endpoint : [10.0.0.2]                    

INFO[2021-02-18T19:30:59Z]orchestrationapi.go:153 RequestService                                              

INFO[2021-02-18T19:30:59Z]orchestrationapi.go:150 RequestService [1] Id       : edge-orchestration-5c2e65bb-8ce8-40c8-bf48-248bf766ba9e 

INFO[2021-02-18T19:30:59Z]orchestrationapi.go:151 RequestService [1] ExecType : container                     

INFO[2021-02-18T19:30:59Z]orchestrationapi.go:152 RequestService [1] Endpoint : [192.168.1.29 10.0.0.1]       

INFO[2021-02-18T19:30:59Z]orchestrationapi.go:153 RequestService                                              

INFO[2021-02-18T19:30:59Z]restclient.go:126 DoGetScoreRemoteDevice [restclient] DoGetScoreRemoteDevice : endpoint[10.0.0.2] 

INFO[2021-02-18T19:30:59Z]restclient.go:151 DoGetScoreRemoteDevice [restclient] respMsg From [10.0.0.2] : map[ScoreValue:10.72922950390001] 

INFO[2021-02-18T19:30:59Z]orchestrationapi.go:331 func3 [orchestrationapi] deviceScore               

INFO[2021-02-18T19:30:59Z]orchestrationapi.go:332 func3 candidate Id       : edge-orchestration-235d74e7-c62c-464c-8bd8-74443ef41e0c 

INFO[2021-02-18T19:30:59Z]orchestrationapi.go:333 func3 candidate ExecType : container               

INFO[2021-02-18T19:30:59Z]orchestrationapi.go:334 func3 candidate Endpoint : 10.0.0.2                

INFO[2021-02-18T19:30:59Z]orchestrationapi.go:335 func3 candidate score    : 10.72922950390001       

INFO[2021-02-18T19:30:59Z]restclient.go:67 DoExecuteRemoteDevice [restclient] DoExecuteRemoteDevice : endpoint[10.0.0.2] 

INFO[2021-02-18T19:30:59Z]restclient.go:90 DoExecuteRemoteDevice [restclient] respMsg From [10.0.0.2] : map[Status:Started] 

INFO[2021-02-18T19:30:59Z]orchestrationapi.go:238 RequestService [orchestrationapi]  [{edge-orchestration-235d74e7-c62c-464c-8bd8-74443ef41e0c 10.0.0.2 10.72922950390001 map[] container}] 

INFO[2021-02-18T19:30:59Z]route.go:130 func1 From [[::1]:35426] POST /api/v1/orchestration/services APIV1RequestServicePost 963.373316ms 
```

### Request

```
curl -X POST "192.168.0.222:56001/api/v1/orchestration/services" -H "accept: application/json" -H "Content-Type: application/json" -d '{ "ServiceName": "hello-world", "ServiceInfo": [{ "ExecutionType": "container", "ExecCmd": [ "docker", "run", "-v", "/var/run:/var/run:rw", "hello-world"]}], "StatusCallbackURI": "http://localhost:8888/api/v1/services/notification", "SelfSelection" : "false"}'

{"Message":"ERROR_NONE","RemoteTargetInfo":{"ExecutionType":"container","Target":"10.0.0.1"},"ServiceName":"hello-world"}
```

### Sub System Edge Orchestration Logs

```
INFO[2021-02-18T19:37:07Z]orchestrationapi.go:122 RequestService [RequestService] hello-world: [{container [docker run -v /var/run:/var/run:rw hello-world] map[]}] 

INFO[2021-02-18T19:37:07Z]orchestrationapi.go:148 RequestService [RequestService] getCandidate                

INFO[2021-02-18T19:37:07Z]orchestrationapi.go:150 RequestService [0] Id       : edge-orchestration-235d74e7-c62c-464c-8bd8-74443ef41e0c 

INFO[2021-02-18T19:37:07Z]orchestrationapi.go:151 RequestService [0] ExecType : container                     

INFO[2021-02-18T19:37:07Z]orchestrationapi.go:152 RequestService [0] Endpoint : [192.168.0.222 10.0.0.2]      

INFO[2021-02-18T19:37:07Z]orchestrationapi.go:153 RequestService                                              

INFO[2021-02-18T19:37:07Z]orchestrationapi.go:150 RequestService [1] Id       : edge-orchestration-5c2e65bb-8ce8-40c8-bf48-248bf766ba9e 

INFO[2021-02-18T19:37:07Z]orchestrationapi.go:151 RequestService [1] ExecType : container                     

INFO[2021-02-18T19:37:07Z]orchestrationapi.go:152 RequestService [1] Endpoint : [10.0.0.1]                    

INFO[2021-02-18T19:37:07Z]orchestrationapi.go:153 RequestService                                              

INFO[2021-02-18T19:37:07Z]restclient.go:126 DoGetScoreRemoteDevice [restclient] DoGetScoreRemoteDevice : endpoint[10.0.0.1] 

INFO[2021-02-18T19:37:07Z]restclient.go:151 DoGetScoreRemoteDevice [restclient] respMsg From [10.0.0.1] : map[ScoreValue:10.418973263495161] 

INFO[2021-02-18T19:37:07Z]orchestrationapi.go:331 func3 [orchestrationapi] deviceScore               

INFO[2021-02-18T19:37:07Z]orchestrationapi.go:332 func3 candidate Id       : edge-orchestration-5c2e65bb-8ce8-40c8-bf48-248bf766ba9e 

INFO[2021-02-18T19:37:07Z]orchestrationapi.go:333 func3 candidate ExecType : container               

INFO[2021-02-18T19:37:07Z]orchestrationapi.go:334 func3 candidate Endpoint : 10.0.0.1                

INFO[2021-02-18T19:37:07Z]orchestrationapi.go:335 func3 candidate score    : 10.418973263495161      

INFO[2021-02-18T19:37:07Z]restclient.go:67 DoExecuteRemoteDevice [restclient] DoExecuteRemoteDevice : endpoint[10.0.0.1] 

INFO[2021-02-18T19:37:09Z]restclient.go:90 DoExecuteRemoteDevice [restclient] respMsg From [10.0.0.1] : map[Status:Started] 

INFO[2021-02-18T19:37:09Z]orchestrationapi.go:238 RequestService [orchestrationapi]  [{edge-orchestration-5c2e65bb-8ce8-40c8-bf48-248bf766ba9e 10.0.0.1 10.418973263495161 map[] container}] 

INFO[2021-02-18T19:37:09Z]route.go:130 func1 From [192.168.0.222:53028] POST /api/v1/orchestration/services APIV1RequestServicePost 1.956543799s 
```

# Logic behind the fix

1. The problem was there because of multiple network interface events from kernel in a short time
2. Because of this during the disconnection the map would some times get cleared and thus IPs were lost resulting in faliure during GET/POST/Scoring
3. Thus, a system level command ifconfig was replaced by go packages that give the IP details neatly and avoid multiple events
4. New connections and Disconnections  were treated alike and network info was reset in both cases as in both cases it needs to be changed.
5. Other methods like timeouts, Retry Logics and IP Comparison in code was also tested for the fix but this fix looked neater and worked on the root cause thus this was raised.

```
Example
1. Describe the reproduction procedures freely.
2. Or list up the test description like :
  - [X] Unittest
  - [X] Execution of Container
  - [X] Execution on top of Native
```

**Test environment configuration:**
* Firmware version:  Ubuntu 16.04
* Hardware: x86-64
* Toolchain: Go 15.1
* Edge Orchestration Release:  Coconut

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/controller/discoverymgr/mnedc/tunmgr/tun.go [hunk 1]
```diff
@@ -19,11 +19,12 @@ package tunmgr
 
 import (
 	"fmt"
+	"github.com/lf-edge/edge-home-orchestration-go/src/common/logmgr"
```
Comment (t25kim) [inline src/controller/discoverymgr/mnedc/tunmgr/tun.go:22]: Don't move this line of code, it might be conflict with #272

File: src/controller/discoverymgr/mnedc/tunmgr/tun.go [hunk 2]
```diff
@@ -36,7 +37,7 @@ var (
 )
 
 func init() {
-	// Do nothing because there is no need to initialize anything
```
Comment (t25kim) [inline src/controller/discoverymgr/mnedc/tunmgr/tun.go:39]: Do you have a reason to get rid of this line?

**Review by t25kim — CHANGES_REQUESTED** [review]
Thanks for the PR. Please take a look at my comments.

**Comment by MoonkiHong** [comment]
@sun-sharma I strongly do not agree that this is not only the bug fix, since as you described in the `logic behind the fix` and what we have seen, this is a logic change and leads to an massive change. Please revise the current commit message with including (and rectifying) this differentiation including the category 1~4 in the `logic behind the fix`.

**Review by MoonkiHong — CHANGES_REQUESTED** [review]
@sun-sharma I strongly do not agree that this is not only the bug fix, since as you described in the logic behind the fix and what we have seen, this is a logic change and leads to an massive change. Please revise the current commit message with including (and rectifying) this differentiation including the category 1~4 in the logic behind the fix.

File: src/controller/discoverymgr/mnedc/tunmgr/tun.go (hunk 2 above)
Comment (sun-sharma) [reply src/controller/discoverymgr/mnedc/tunmgr/tun.go:39]: No, I will revert this.

File: src/controller/discoverymgr/mnedc/tunmgr/tun.go (hunk 1 above)
Comment (sun-sharma) [reply src/controller/discoverymgr/mnedc/tunmgr/tun.go:22]: Ok.

**Comment by sun-sharma** [comment]
Thanks Peter/Taewan for the review. I will make the suggested changes.

**Comment by sun-sharma** [comment]
> @sun-sharma I strongly do not agree that this is not only the bug fix, since as you described in the logic behind the fix and what we have seen, this is a logic change and leads to an massive change. Please revise the current commit message with including (and rectifying) this differentiation including the category 1~4 in the logic behind the fix.

How about : [MNEDC] Implementation of a method to overcome multiple kernel interrupts which leads to device/service undiscoverable

**Comment by t25kim** [comment]
> > @sun-sharma I strongly do not agree that this is not only the bug fix, since as you described in the logic behind the fix and what we have seen, this is a logic change and leads to an massive change. Please revise the current commit message with including (and rectifying) this differentiation including the category 1~4 in the logic behind the fix.
> 
> How about : [MNEDC] Implementation of a method to overcome multiple kernel interrupts which leads to device/service undiscoverable

`Implementation of a method to overcome multiple kernel interrupts which leads to device/service undiscoverable` is a bug.
It doesn’t matter if you write the bug details in a commit, however you should write key features or messages in.
If me, I would add lines below to the commit.
```
[MNEDC] Bug fix while Network Change
- Reset DB regarding connected devices when new and del events regarding IPv4 address are up
- SetTUNIP() : Implemented by golang API that give the IP details instead of external ifconfig command
- detectionHandler() returns true when new and deleted events up
```
Hope this helps you.

**Comment by sun-sharma** [comment]
Did the following : 

1. Added Description to PR and to the commit
2. Changed the Title as suggested
3. Made code changes as per review changes.

**Review by t25kim — APPROVED** [review]
LGTM. Thanks!

File: src/controller/discoverymgr/mnedc/tunmgr/tun.go [hunk 3]
```diff
@@ -53,15 +54,29 @@ func GetInstance() Tun {
...
+	laddr, err := netlink.ParseAddr(fmt.Sprintf("%s/%d",localAddr.String(),maskLen))
+	if err != nil {
+		return err
+	}
+	err = netlink.AddrAdd(link, laddr)
+	if err != nil {
+		return err
+	}
+	return nil
 }
```
Comment (tdrozdovsky) [inline src/controller/discoverymgr/mnedc/tunmgr/tun.go:81]: If possible, consider replacing and following lines of code in other PR!

File: src/controller/discoverymgr/mnedc/tunmgr/tun.go [hunk 4]
```diff
@@ -53,15 +54,29 @@ func GetInstance() Tun {
...
+	})
+
 	return intf, err
 }
 
 //SetTUNIP sets an IP to the interface
 func (TunImpl) SetTUNIP(iName string, localAddr net.IP, addr *net.IPNet, debug bool) error {
-	sargs := fmt.Sprintf("%s %s netmask %s", iName, localAddr.String(), net.IP(addr.Mask).String())
-	args := strings.Split(sargs, " ")
-	return commandExec("ifconfig", args, debug)
```
Comment (tdrozdovsky) [inline src/controller/discoverymgr/mnedc/tunmgr/tun.go:64]: Thank you for changing these lines of code. This is a potential security vulnerability.

**Review by tdrozdovsky — APPROVED** [review]
LGTM!

**Comment by sun-sharma** [comment]
> @sun-sharma I strongly do not agree that this is not only the bug fix, since as you described in the logic behind the fix and what we have seen, this is a logic change and leads to an massive change. Please revise the current commit message with including (and rectifying) this differentiation including the category 1~4 in the logic behind the fix.

Hi @MoonkiHong, I had changes the Description and Title as you had told. Please take a look , Thank you !

**Review by MoonkiHong — APPROVED** [review]
+1
