### PR TITLE
Delete connection refused device info from netDB

### LINKED ISSUE #109: Ping to offline devices consistently to update RTT
**Describe the bug**
The Edge Orchestrator ping to offline devices to check RTT values consistently.
```
2020/07/16 22:58:50 discovery.go:374:
2020/07/16 22:58:54 helper.go:99: [http://10.113.71.53:56002/api/v1/ping] reqeust get failed !!, err = Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
2020/07/16 22:58:59 helper.go:99: [http://10.113.71.53:56002/api/v1/ping] reqeust get failed !!, err = Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
2020/07/16 22:59:04 helper.go:99: [http://10.113.71.53:56002/api/v1/ping] reqeust get failed !!, err = Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
2020/07/16 22:59:09 helper.go:99: [http://10.113.71.53:56002/api/v1/ping] reqeust get failed !!, err = Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
2020/07/16 22:59:14 helper.go:99: [http://10.113.71.53:56002/api/v1/ping] reqeust get failed !!, err = Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
2020/07/16 22:59:19 helper.go:99: [http://10.113.71.53:56002/api/v1/ping] reqeust get failed !!, err = Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
2020/07/16 22:59:24 helper.go:99: [http://10.113.71.53:56002/api/v1/ping] reqeust get failed !!, err = Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
2020/07/16 22:59:29 helper.go:99: [http://10.113.71.53:56002/api/v1/ping] reqeust get failed !!, err = Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
2020/07/16 22:59:34 helper.go:99: [http://10.113.71.53:56002/api/v1/ping] reqeust get failed !!, err = Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
```

**To Reproduce**
1. Set up a connection between devices.
2. Check logs after keeping a device offline

**Expected behavior**
The Edge Orchestrator should delete an offline device info from net DB and ping to online devices only.

**Test environment configuration (please complete the following information):**
* Firmware version: Ubuntu 16.04
* Hardware: x86-64
* Edge Orchestration Release: Baobab

### PR DESCRIPTION
**Pull request by t25kim**
# Description

The Edge Orchestrator deletes the offline device info from netDB if RTT fails twice in a row.
This PR sets the RTT value to a negative when RTT first fails, and deletes device information if RTT fails consecutively.

Fixes #109 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
1. Set up a connection between devices.
2. Check logs after keeping a device offline
```
2020/07/20 06:28:58 helper.go:99: [http://10.113.71.53:56002/api/v1/ping] reqeust get failed !!, err = Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
2020/07/20 06:28:58 roundtriptime.go:84: Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
2020/07/20 06:29:03 helper.go:99: [http://10.113.71.53:56002/api/v1/ping] reqeust get failed !!, err = Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
2020/07/20 06:29:03 roundtriptime.go:84: Get "http://10.113.71.53:56002/api/v1/ping": dial tcp 10.113.71.53:56002: connect: connection refused
2020/07/20 06:29:03 roundtriptime.go:65: resourceutil Delete edge-orchestration-f323e2a4-624b-4eb7-8da2-a6b9b2813415
```

**Test Configuration**:
* Firmware version: Ubuntu 16.04
* Hardware: x86-64
* Edge Orchestration Release: Baobab

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/common/resourceutil/roundtriptime.go [hunk 1]
```diff
@@ -61,8 +61,13 @@ func processRTT() {
 				}
 				go func(info netDB.NetworkInfo) {
 					result := selectMinRTT(ch, totalCount)
-					info.RTT = result
-					netDBExecutor.Update(info)
+					if info.RTT < 0 && result < 0 {
```
Comment (MoonkiHong) [inline src/common/resourceutil/roundtriptime.go:64]: @suresh-lc PTAL. It seems to me that it prevents undesired iteration of discovery trials for the dead devices, so that it improves the efficiency of energy consumption and data storage of the edge device. Current proposal is based on the fixed policy (like allowing 1 iteration once it fails the discovery) and in the mid-long term approach, we might need to develop it based on sth like AI/ML. So my opinion is okay for accepting this as the 1st proposal.

Comment (suresh-lc) [reply src/common/resourceutil/roundtriptime.go:64]: Checking on the issue. But i do find this in discovery.go (line 364)
if data.TTL == 0 {
					deleteDevice(data.DeviceID)
					continue
				}
So it deletes a device whose TTL is 0 while multicasting.

Comment (t25kim) [reply src/common/resourceutil/roundtriptime.go:64]: @suresh-lc Thank you for the comment. 
I think that source code deletes a device that respond to multicast with TTL=0.
However this issue is not related on the code since offline devices couldn't respond to the multicast and the deviceDetectionRoutine function does not check netDB to delete them.

Comment (suresh-lc) [reply src/common/resourceutil/roundtriptime.go:64]: Consider a scenario of a device becomes offline for short while and again comes alive. Going with the suggested approach, we would be deleting the device from netDB and again add. And if this happens frequently, then unnecessary delete and add happens. And that too if its too regular, its overhead. So might be we can add a timers and re-try count of 2 or so. What is your opinion.

Comment (t25kim) [reply src/common/resourceutil/roundtriptime.go:64]: @suresh-lc It makes sense. 
RTT ping cycle is 5 sec. How about giving it 12 chances (around 1min)? It might be good to have a limit variable on the code as well.

Comment (suresh-lc) [reply src/common/resourceutil/roundtriptime.go:64]: Guess 1min approach is good. Just to verify completely, you can check on below :
Scenario:
1. Device 1 and device 2 are there .

2. Both discovered each other.

3. Now device 2 is disconnected from network so, device 1 is not able to ping it. ( as per  his logic he will remove device 2 from discovered device list of device 1) 

3. Device 2 again connected to network...is device 1 able to discover it freshly?

If this we tested, we are good to go ahead and check in the changes.

**Comment by t25kim** [comment]
@suresh-lc Even if the devices lost their connection, they try to look for neighbors 
periodically via Advertisement() or deviceDetectionRoutine() of the discovery mangager.
I've tested the scenario with 2 devices on ubuntu and on RPi and it works well.
