### PR TITLE
[DataStorage] Use Official device SDK 1.4.0 and remove redirection

### LINKED ISSUE #231: [DataStorage] Runtime error
**Describe the bug**
A runtime error when edgex foundry servers are not running, 
```
level=ERROR ts=2021-01-19T01:51:50.815737266Z app=datastorage source=init.go:154 msg="Get \"http://localhost:48080/api/v1/ping\": dial tcp 127.0.0.1:48080: connect: connection refused"
level=INFO ts=2021-01-19T01:51:51.817181193Z app=datastorage source=init.go:144 msg="Check Metadata service's status by ping..."
level=INFO ts=2021-01-19T01:51:51.818287982Z app=datastorage source=init.go:144 msg="Check Data service's status by ping..."
level=ERROR ts=2021-01-19T01:51:51.822577012Z app=datastorage source=init.go:154 msg="Get \"http://localhost:48081/api/v1/ping\": dial tcp 127.0.0.1:48081: connect: connection refused"
level=ERROR ts=2021-01-19T01:51:51.824049381Z app=datastorage source=init.go:154 msg="Get \"http://localhost:48080/api/v1/ping\": dial tcp 127.0.0.1:48080: connect: connection refused"
level=INFO ts=2021-01-19T01:51:52.825768174Z app=datastorage source=init.go:144 msg="Check Metadata service's status by ping..."
level=INFO ts=2021-01-19T01:51:52.826907105Z app=datastorage source=init.go:144 msg="Check Data service's status by ping..."
level=ERROR ts=2021-01-19T01:51:52.830784824Z app=datastorage source=init.go:154 msg="Get \"http://localhost:48081/api/v1/ping\": dial tcp 127.0.0.1:48081: connect: connection refused"
level=ERROR ts=2021-01-19T01:51:52.83209855Z app=datastorage source=init.go:154 msg="Get \"http://localhost:48080/api/v1/ping\": dial tcp 127.0.0.1:48080: connect: connection refused"
INFO[2021-01-19T01:51:53Z]discovery.go:833 activeDiscovery [discoverymgr] activeDiscovery!!!
INFO[2021-01-19T01:51:53Z]discovery.go:571 func1 [deviceDetectionRoutine] edge-orchestration-3125da9e-1e9a-41aa-ac83-004725eb2d1e
level=ERROR ts=2021-01-19T01:51:53.83359109Z app=datastorage source=init.go:139 msg="dependency Metadata service checking time out"
level=ERROR ts=2021-01-19T01:51:53.834663766Z app=datastorage source=init.go:139 msg="dependency Data service checking time out"
level=INFO ts=2021-01-19T01:51:53.840074015Z app=datastorage source=httpserver.go:116 msg="Web server shutting down"
level=INFO ts=2021-01-19T01:51:53.841736032Z app=datastorage source=httpserver.go:107 msg="Web server stopped"
level=INFO ts=2021-01-19T01:51:54.341966491Z app=datastorage source=httpserver.go:118 msg="Web server shut down"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8d1a0e]

goroutine 44 [running]:
github.com/edgexfoundry/device-sdk-go/internal/autoevent.(*manager).StopAutoEvents(0x0)
        /home/t25kim/edge-home-orchestration-go/vendor/github.com/edgexfoundry/device-sdk-go/internal/autoevent/manager.go:69 +0x4e
github.com/edgexfoundry/device-sdk-go/pkg/service.(*DeviceService).Stop(0xc0004c2780, 0xc0005ae600)
        /home/t25kim/edge-home-orchestration-go/vendor/github.com/edgexfoundry/device-sdk-go/pkg/service/service.go:134 +0x45
github.com/edgexfoundry/device-sdk-go/pkg/service.Main(0xe2dbda, 0xb, 0xe3a91d, 0x1a, 0xda46e0, 0xc0005a5de0, 0xf46e20, 0xc0005ae600, 0xc0000330a0, 0xc0005ac300, ...)
        /home/t25kim/edge-home-orchestration-go/vendor/github.com/edgexfoundry/device-sdk-go/pkg/service/main.go:69 +0x6fa
github.com/edgexfoundry/device-sdk-go/pkg/startup.Bootstrap(0xe2dbda, 0xb, 0xe3a91d, 0x1a, 0xda46e0, 0xc0005a5de0)
        /home/t25kim/edge-home-orchestration-go/vendor/github.com/edgexfoundry/device-sdk-go/pkg/startup/bootstrap.go:19 +0x117
created by github.com/lf-edge/edge-home-orchestration-go/src/controller/storagemgr.StorageImpl.StartStorage
        /home/t25kim/edge-home-orchestration-go/src/controller/storagemgr/storage.go:51 +0xef
```

**To Reproduce**
1. Put necessary configuration files in /var/edge-orchestration/datastorage/
2. Run edge-home-orchestration-go

**Expected behavior**
Check the edgex foundry server in advance before starting Data Storage.

**Test environment configuration (please complete the following information):**
* Firmware version: Ubuntu 18.04
* Hardware: x86-64
* Edge Orchestration Release: Coconut

### PR DESCRIPTION
**Pull request by nitu-s-gupta**
Signed-off-by: Nitu Gupta <nitu.gupta@samsung.com>

# Description

Edge Orchestration uses edgexfoundry/device-sdk-go from github.com/hahattan/device-sdk-go v1.4.1, not the official repository, So the official repository used and checked for metadata running to avoid the locks issue in Hanoi release of EdgeX

Fixes #231 

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
1. Edge-orchestration checks for Metadata IP address from configuration.toml file
2. It pings to the url to check if metadata is running
3. If the metadata is running, the datastorage is started else Error log is printed and datastorage is not started
4. Build the code and run
5. Stop the metadata and check. Error log is printed as expected 
6. Start metadata and rerun edge-orchestration. Device service started and POST/GET APIs working as expected

**Test Configuration**:
* OS type & version: (Ubuntu 20.04)
* Hardware: (x86-64)
* Edge Orchestration Release: (1.0.0)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: internal/controller/storagemgr/storage.go [hunk 1]
```diff
@@ -74,8 +80,29 @@ func (s *StorageImpl) GetStatus() int {
...
+	ip, port, err := config.GetMetadataServerIP(dataStorageConfFolder + "/configuration.toml")
+	if err != nil {
+		fmt.Println(err)
+	}
+	timeout := time.Duration(1 * time.Second)
+	client := http.Client{
+		Timeout: timeout,
+	}
+	url := "http://" + ip + ":" + fmt.Sprint(port) + "/api/v1/ping"
+	resp, err := client.Get(url)
```
Comment (t25kim) [inline internal/controller/storagemgr/storage.go:94]: What about using [MakeTargetURL](https://github.com/lf-edge/edge-home-orchestration-go/blob/e75c75eba915fe7772e56c9ce53769bd70a96bf3/internal/restinterface/resthelper/helper.go#L210) and [DoGet](https://github.com/lf-edge/edge-home-orchestration-go/blob/e75c75eba915fe7772e56c9ce53769bd70a96bf3/internal/restinterface/resthelper/helper.go#L96) functions?

File: internal/controller/storagemgr/storage.go [hunk 2]
```diff
@@ -74,8 +80,29 @@ func (s *StorageImpl) GetStatus() int {
 	return s.status
 }
 
+// checkMetadataStatus checks for metadata running to start DataStorage
+func checkMetadataStatus() bool {
+	ip, port, err := config.GetMetadataServerIP(dataStorageConfFolder + "/configuration.toml")
+	if err != nil {
+		fmt.Println(err)
```
Comment (t25kim) [inline internal/controller/storagemgr/storage.go:87]: Is `return` unnecessary?

File: internal/controller/storagemgr/storage.go [hunk 3]
```diff
@@ -74,8 +80,29 @@ func (s *StorageImpl) GetStatus() int {
...
+	timeout := time.Duration(1 * time.Second)
+	client := http.Client{
+		Timeout: timeout,
+	}
+	url := "http://" + ip + ":" + fmt.Sprint(port) + "/api/v1/ping"
+	resp, err := client.Get(url)
+	if err == nil && resp.StatusCode == 200 {
+		return true
+	}
+	log.Println(logPrefix, "Metadata is not running!!!")
```
Comment (t25kim) [inline internal/controller/storagemgr/storage.go:98]:
```suggestion
	log.Warn(logPrefix, "Metadata is not running!!!")
```

File: internal/controller/storagemgr/storage.go [hunk 4]
```diff
@@ -74,8 +80,29 @@ func (s *StorageImpl) GetStatus() int {
...
+	return false
+
+}
+
 // StartStorage starts a server in terms of DataStorage
 func (s *StorageImpl) StartStorage(host string) (err error) {
+
```
Comment (t25kim) [inline internal/controller/storagemgr/storage.go:105]: Please delete this blank line.

**Review by t25kim — COMMENTED** [review]
Thanks for the contribution!
Please take a look at my comments.

**Review by tdrozdovsky — CHANGES_REQUESTED** [review]

File: internal/controller/storagemgr/storage.go (hunk 2 above)
Comment (nitu-s-gupta) [reply internal/controller/storagemgr/storage.go:87]: return of GetMetadataServerIp or checkMetadataStatus?

[the remark this answers is not in the document]
Comment (nitu-s-gupta) [reply internal/controller/storagemgr/storage.go:87]: Done!

File: internal/controller/storagemgr/storage.go (hunk 1 above)
Comment (nitu-s-gupta) [reply internal/controller/storagemgr/storage.go]: Done!

File: internal/controller/storagemgr/storage.go (hunk 3 above)
Comment (nitu-s-gupta) [reply internal/controller/storagemgr/storage.go]: Done!

File: internal/controller/storagemgr/storage.go (hunk 4 above)
Comment (nitu-s-gupta) [reply internal/controller/storagemgr/storage.go]: Done!

File: internal/controller/storagemgr/config/toml.go [hunk 5]
```diff
@@ -179,3 +179,13 @@ func GetServerIP(ConfigPath string) (string, int, error) {
...
 }
+
+// GetMetadataServerIP is used to obtain the IP and port number of Metadata
+func GetMetadataServerIP(ConfigPath string) (string, int, error) {
+	config, err := toml.LoadFile(ConfigPath)
+	if err != nil {
+		return "", 0, err
+	}
+	return config.Get("Clients.Metadata.Host").(string), (int)(config.Get("Clients.Metadata.Port").(int64)), nil
+
```
Comment (tdrozdovsky) [inline internal/controller/storagemgr/config/toml.go:190]: Please delete this blank line.

File: internal/controller/storagemgr/storage.go [hunk 6]
```diff
@@ -19,21 +19,27 @@ package storagemgr
...
 )
 
 const (
 	dataStorageService    = "datastorage"
 	dataStorageConfFolder = "res"
 	deviceIDFilePath      = "/var/edge-orchestration/device/orchestration_deviceID.txt"
+	pingAPI               = "/api/v1/ping"
 )
 
+const logPrefix = "[storagemgr]"
```
Comment (tdrozdovsky) [inline internal/controller/storagemgr/storage.go:41]: Move `logPrefix` to the const block above

File: internal/controller/storagemgr/storage.go [hunk 7]
```diff
@@ -74,6 +83,22 @@ func (s *StorageImpl) GetStatus() int {
...
+		log.Warn("Error", err)
+	}
+	targetURL := helper.MakeTargetURL(metadataIP, metadataPort, pingAPI)
+	_, statusCode, err := helper.DoGet(targetURL)
+	if err == nil && statusCode == 200 {
+		return true
+	}
+	log.Warn("Metadata is not running!!")
+	return false
+
```
Comment (tdrozdovsky) [inline internal/controller/storagemgr/storage.go:99]: Please delete this blank line 99

**Review by tdrozdovsky — CHANGES_REQUESTED** [review]
It's final my comments! Thank you!

**Review by tdrozdovsky — APPROVED** [review]
LGTM!

File: internal/controller/storagemgr/storage.go (hunk 2 above)
Comment (t25kim) [reply internal/controller/storagemgr/storage.go]: I meant there must be a 'return false' after the log.

**Review by t25kim — APPROVED** [review]
LGTM Thanks!

**Review by MoonkiHong — APPROVED** [review]
+1
