### PR TITLE
Fix accessible confidential information that is recorded in unencrypt…

### LINKED ISSUE #141: [WIP] Encryption of SecureMgr
_Originally posted by @tdrozdovsky in https://github.com/lf-edge/edge-home-orchestration-go/issues/131#issuecomment-691930137_

> 
> 
> I personally think that sensitive data is returned by an access to `passPhraseJWTPath`. What do you think? @tdrozdovsky
> 
> https://github.com/lf-edge/edge-home-orchestration-go/blob/22ce49b4b76ae78dfb75e14ef64399e5805c7d02/src/controller/securemgr/authenticator/authenticator.go#L70
> 
> This might be the same potential security risk as follow.
> 
> https://github.com/lf-edge/edge-home-orchestration-go/blob/22ce49b4b76ae78dfb75e14ef64399e5805c7d02/src/controller/securemgr/authenticator/authenticator.go#L84

Good point, I know and remember this security issue.

These only informs about a failed attempt to create the `passPhraseJWTFilePath` file.
But of course, storing such information in files (passPhrase, edge-orchestration.key, etc) is a security risk.
I think in the future this should be solved with secure storage or with access control system such as: SeLinux, SMACK, etc.

Thank you for reminder

### PR DESCRIPTION
**Pull request by tdrozdovsky**
…ed form

Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

File names were removed from logging in accordance with the Common Weakness Enumeration: CWE-312, CWE-315. In this case, there were no security threats, but automatic vulnerability analysis systems recommend doing this.

Fixes #141

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Run LGTM checker

**Test Configuration**:
* Firmware version: Ubuntu 16.04, etc.)
* Hardware: x86-64
* Toolchain: Docker and Go recommended versions
* Edge Orchestration Release: Coconut

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by t25kim — APPROVED** [review]
LGTM!

**Review by MoonkiHong — APPROVED** [review]
This is great! LGTM.

**Review by suresh-lc — APPROVED** [review]
LGTM

File: src/controller/securemgr/authenticator/authenticator.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ func Init(passPhraseJWTPath string) {
 		passphrase = []byte(randString(16))
 		err = ioutil.WriteFile(passPhraseJWTFilePath, passphrase, 0666)
 		if err != nil {
-			log.Println(logPrefix, "cannot create "+passPhraseJWTFilePath+": ", err)
+			log.Println(logPrefix, "Cannot create passPhraseJWT.txt:", err)
```
Comment (mgjeong) [inline src/controller/securemgr/authenticator/authenticator.go:85]: Looks good, but ```'passPhraseJWT.txt'``` also looks like a filename( information).
What about you use just a simple text like ```'passphrase file'```?

**Review by mgjeong — APPROVED** [review]
Good job.

File: src/controller/securemgr/authenticator/authenticator.go (hunk 1 above)
Comment (tdrozdovsky) [reply src/controller/securemgr/authenticator/authenticator.go:85]: @mgjeong Thank you for your good question.
As I wrote earlier, this file should contain a phrase for generating a SHA-based JWT (we recommend using an RSA-based JWT). And this is described in the documentation, hence the attacker knows this.
If you look at the threat tree, then you should **divide the type of attack into remote and with direct access to the device**. At the current moment, the use of the token allows us to **protect against a remote attack**, but not against an attack when there is access to the device.
Of course, our goal is to provide maximum protection, and we will do this step by step.
In the future, I suppose we will store sensitive information in a secure storage.

Comment (mgjeong) [reply src/controller/securemgr/authenticator/authenticator.go:85]: Okay. I got it.
Thanks.
