### PR TITLE
Fix the build error occurred for arm architecture on PC

### LINKED ISSUE #155: Build error occurred in arm architecture
**Describe the bug**
During  `$./build.sh container arm` or  `$./build.sh container arm64`, I got the following build error.
```
**********************************
 Create Docker container
**********************************

Error: No such container: edge-orchestration
Error: No such image: edge-orchestration:baobab
docker build --tag edge-orchestration:baobab --file /home/t25kim/work/edge-home-orchestration-go/GoMain/Dockerfile --build-arg PLATFORM=arm32v7 .
Sending build context to Docker daemon  301.4MB
Step 1/17 : ARG PLATFORM
Step 2/17 : FROM $PLATFORM/ubuntu:16.04
 ---> 8eedc387cb89
Step 3/17 : ENV TARGET_DIR=/edge-orchestration
 ---> Using cache
 ---> 5f0a61e388ca
Step 4/17 : ENV HTTP_PORT=56001
 ---> Using cache
 ---> b067bb7683b3
Step 5/17 : ENV MDNS_PORT=5353
 ---> Using cache
 ---> 075a5c1d1c28
Step 6/17 : ENV MNEDC_PORT=8000
 ---> Using cache
 ---> c2bc2afb2a0a
Step 7/17 : ENV MNEDC_BROADCAST_PORT=3333
 ---> Using cache
 ---> 5730d8bb2687
Step 8/17 : ENV ZEROCONF_PORT=42425
 ---> Using cache
 ---> b6b101e9d328
Step 9/17 : ENV APP_MAIN_DIR=GoMain
 ---> Using cache
 ---> b6d791035071
Step 10/17 : ENV APP_BIN_DIR=$APP_MAIN_DIR/bin
 ---> Using cache
 ---> e178739df475
Step 11/17 : ENV APP_NAME=edge-orchestration
 ---> Using cache
 ---> e75f9b70dc2c
Step 12/17 : RUN apt update
 ---> Running in 244a90de8ea7
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/sh -c apt update' returned a non-zero code: 1
Makefile:94: recipe for target 'build-container' failed
make: *** [build-container] Error 1
```

**To Reproduce**
 `$./build.sh container arm` or  `$./build.sh container arm64`

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

Due to the installation of packages in a Dockerfile, the build for arm architectures was not successful. To fix the error, added the use of the Qemu. 
P.S. It should be noted that installing packages during container creation is not the best approach. It is better to use an image with the packages installed.

Fixes #155 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Documentation update

# How Has This Been Tested?
```
$ ./build.sh container arm
```
or
```
$ ./build.sh container arm64
```
Expected: successful build

**Test Configuration**:
* Firmware version: Ubuntu 16.04, Ubuntu 20.04
* Hardware: x86-64, ARM, ARM64
* Toolchain: Docker recommended version and Go 1.15.5 version
* Edge Orchestration Release: Coconut

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: build.sh [hunk 1]
```diff
@@ -401,9 +402,13 @@ function build_docker_container() {
             ;;
         arm)
             CONTAINER_ARCH="arm32v7"
+            cp $BASE_DIR/GoMain/dockerfiles/Dockerfile_qemu_arm $BASE_DIR/GoMain/Dockerfile
+            cp /usr/bin/qemu-arm-static $BASE_DIR/GoMain/
```
Comment (t25kim) [inline build.sh:406]:
```suggestion
            cp /usr/bin/qemu-arm-static $BASE_DIR/GoMain/bin/qemu
```

File: build.sh [hunk 2]
```diff
@@ -401,9 +402,13 @@ function build_docker_container() {
...
             ;;
         arm64)
             CONTAINER_ARCH="arm64v8"
+            cp $BASE_DIR/GoMain/dockerfiles/Dockerfile_qemu_aarch64 $BASE_DIR/GoMain/Dockerfile
+            cp /usr/bin/qemu-aarch64-static $BASE_DIR/GoMain/
```
Comment (t25kim) [inline build.sh:411]:
```suggestion
            cp /usr/bin/qemu-aarch64-static $BASE_DIR/GoMain/bin/qemu
```

File: GoMain/dockerfiles/Dockerfile_qemu_aarch64 [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+ENV MNEDC_PORT=3334
+ENV MNEDC_BROADCAST_PORT=3333
+ENV ZEROCONF_PORT=42425
+ENV APP_MAIN_DIR=GoMain
+ENV APP_BIN_DIR=$APP_MAIN_DIR/bin
+ENV APP_NAME=edge-orchestration
+
+# copy files
+COPY $APP_BIN_DIR/$APP_NAME $APP_MAIN_DIR/run.sh $TARGET_DIR/
+COPY $APP_MAIN_DIR/qemu-aarch64-static /usr/bin/
```
Comment (t25kim) [inline GoMain/dockerfiles/Dockerfile_qemu_aarch64:21]: Assume that this file is the Dockerfile in the GoMain folder.
We can copy files related to qemu like below.
```suggestion
COPY $APP_QEMU_DIR/ /usr/bin/
```

File: doc/platforms/raspberry_pi3/raspberry_pi3.md [hunk 4]
```diff
@@ -28,13 +28,19 @@ There are two options for building a edge-orchestration container:
 1. On your PC and downloading the edge-orchestration container image from the `edge-orchestration.tar` archive (recommended).
 2. Build directly on the Raspberry Pi 3 board.
 ### 1. Using your PC
+
+Prerequisites: install the qemu packages
+```shell
+$ sudo apt-get install qemu binfmt-support qemu-user-static
+```
+
 Run the `./build.sh` script and specify the build parameters - `container`,  architecture - `arm64`  (in the case of building in protected mode, add `secure`), see examples below:
```
Comment (t25kim) [inline doc/platforms/raspberry_pi3/raspberry_pi3.md:37]: Please fix from 'arm64' to 'arm'
```suggestion
Run the `./build.sh` script and specify the build parameters - `container`,  architecture - `arm`  (in the case of building in protected mode, add `secure`), see examples below:
```

File: GoMain/dockerfiles/Dockerfile_qemu_aarch64 [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+ENV TARGET_DIR=/edge-orchestration
+ENV HTTP_PORT=56001
+ENV MDNS_PORT=5353
+ENV MNEDC_PORT=3334
+ENV MNEDC_BROADCAST_PORT=3333
+ENV ZEROCONF_PORT=42425
+ENV APP_MAIN_DIR=GoMain
+ENV APP_BIN_DIR=$APP_MAIN_DIR/bin
+ENV APP_NAME=edge-orchestration
+
```
Comment (t25kim) [inline GoMain/dockerfiles/Dockerfile_qemu_aarch64:18]:
```suggestion
ENV APP_QEMU_DIR=$APP_BIN_DIR/qemu
```

File: build.sh [hunk 6]
```diff
@@ -392,6 +392,7 @@ function build_docker_container() {
 
     docker rm -f $DOCKER_IMAGE
     docker rmi -f $DOCKER_IMAGE:$CONTAINER_VERSION
+    cp $BASE_DIR/GoMain/dockerfiles/Dockerfile $BASE_DIR/GoMain/Dockerfile
```
Comment (t25kim) [inline build.sh:395]:
```suggestion
    mkdir -p $BASE_DIR/GoMain/bin/qemu
```

File: build.sh (hunk 1 above)
Comment (t25kim) [inline build.sh:406]:
```suggestion
            cp /usr/bin/qemu-arm-static $BASE_DIR/GoMain/bin/qemu
```

File: build.sh (hunk 2 above)
Comment (t25kim) [inline build.sh:411]:
```suggestion
            cp /usr/bin/qemu-aarch64-static $BASE_DIR/GoMain/bin/qemu
```

**Review by t25kim — COMMENTED** [review]
Thank you for the PR!
I suggest my code since we don't need to make several Dockerfile files if we make a folder for qemu files.
Please take a look at my comments and code.

**Review by MoonkiHong — COMMENTED** [review]
_Reference as our discussion: https://github.com/lf-edge/edge-home-orchestration-go/issues/155#issuecomment-717762199_

Instead of create a separate Dockerfile per a given platform, we can use the current Dockerfile for a better usability (due to its simpler approach) if there is a straightforward means to embrace builds on all the target platform, as pointed by @t25kim. The guidance from the above reference is to run qemu on docker instead of pulling qemu binary into a docker image.

**Comment by tdrozdovsky** [comment]
@MoonkiHong @t25kim Thank you, this is a great idea, I completely agree with proposal, I have already corrected and tested on arm, arm64 everything works fine. 
Please note that the `qemu-arch-static` files are still included in the image and the universal build leads to the fact that the image size for arm = 199M; arm64 = 313M. 

P.S. I like working in the community, you can always hear useful advice and other opinions.

**Comment by MoonkiHong** [comment]
> @MoonkiHong @t25kim Thank you, this is a great idea, I completely agree with proposal, I have already corrected and tested on arm, arm64 everything works fine.
> Please note that the `qemu-arch-static` files are still included in the image and the universal build leads to the fact that the image size `edge-orchestraton.tar` for arm = 199M; arm64 = 313M.
> 
> P.S. I like working in the community, you can always hear useful advice and other opinions.

@tdrozdovsky Thank you for your always kind and passionate contributions to our community. Of course we are always open to listen to and adopt all our community opinions for the better advancement of our project. When it comes to the built image size that you pointed out, we could raise the regarding issue with a specific use cases (like the hardware specification restriction). ^^

**Review by t25kim — APPROVED** [review]
LGTM

@tdrozdovsky Thank you for applying my comments to the PR.
Your advice and code always help me a lot too.

**Review by MoonkiHong — APPROVED** [review]
LGTM.

**Review by suresh-lc — APPROVED** [review]
LGTM. @tdrozdovsky : Your constant help in improving the Home Edge is commendable effort.
